### ISSUE TITLE
Project name needs some adjustment to be well searchable

### ISSUE THREAD

**Issue by chrwei** [michaelsproul/xuino#4]
There's already a highly successful and nearly 20 year old software for Unix/Linux called Squid.  http://en.wikipedia.org/wiki/Squid_(software)

Renaming your project would make yours easier to locate.

**Comment by michaelsproul** [comment]
Haha, damn, I hadn't seen that. I originally called it imp but had to rename due to the clash with the Python standard library.

Suggestions are very welcome.

**Comment by michaelsproul** [comment]
@chrwei, I'm thinking of renaming it xuino, pronounced "zwee-no".

Thoughts?

**Comment by chrwei** [comment]
catchy

**Comment by michaelsproul** [comment]
Name changed to Xuino in 874b11142c6932eaf6b5f8ec3d55f801d4afabcf
