### ISSUE TITLE
3rd party libraries

### ISSUE THREAD

**Issue by TileHalo** [michaelsproul/xuino#6]
Where am I supposed to put 3rd party libraries in xuino?

**Comment by michaelsproul** [comment]
At the moment you have to add them to your Arduino installation, which is less than ideal. I'll patch Xuino so it can also read libraries from a user specified directory (thanks for the prompt!).

If you just want to give it a go now, add the libraries to `/usr/share/arduino/libraries` or equivalent. If you're on a platform other than Linux, you'll need to set the path to your Arduino installation with the `arduino_dir`config variable (see: https://github.com/gnusouth/xuino/blob/master/examples/config). In which case, you should add the libraries to `<arduino_dir>/libraries/`.

Once you've done this you just need to depend on the library by adding it to the `LIBRARIES` variable in the generated Makefile.

Let me know how you go.

**Comment by TileHalo** [comment]
I switched back to Ino (I had problems with Arduino uno and Robot_Control, which i deleted from arduino) cause I am bit hurry now. But I will probably try to solve this after my robots are done(I have deadline next weeks wednesday).

**Comment by michaelsproul** [comment]
Ok, good luck with that :)

**Comment by michaelsproul** [comment]
Hey,

I've added support for 3rd party libraries. Sorry it took a while.

You can now add a list of folders as "library directories" by adding them to one of the config files.

E.g.

```
# ~/.xuinorc
[xuino]
library_dirs = /path/folder_1 /path/folder_2
```
