### ISSUE TITLE
.xuinorc file

### ISSUE THREAD

**Issue by dmr** [michaelsproul/xuino#8]
I ran "xuino init" like you mention in the documentation, but it doesn't work:

```
  File "xuino/xuino.py", line 46, in _error
    raise Exception(message)
Exception: Unable to find version.txt
Please explicitly specify a version in ~/.xuinorc or .xuino
```

Where do I find a minimal example for a config file?

**Comment by michaelsproul** [comment]
Hmm, I'll have to look into this more. If you don't have a .xuinorc the version should be detected automatically...

**Comment by michaelsproul** [comment]
Just tried this, and it works for me on Linux. What OS are you using, and where is the Arduino distribution located?

The default search location is `/usr/share/arduino/lib/`, but you'll probably want something different on OS X. You can set the Arduino distribution root per project or globally using `.xuino` or `~/.xuinorc` respectively, which are INI-formatted config files, with the properties listed here:

https://github.com/michaelsproul/xuino/blob/master/examples/config

You'll probably want the `arduino_root` option.

**Comment by dmr** [comment]
Thanks for the reply. Yes, my arduino was in a different location :)
